// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "window.h"

UserInterface::UserInterface() {
  { w = new Fl_Double_Window(520, 490, "Gerador em C++ de Aplica\303\247\303\243o Web/Mobile");
    w->user_data((void*)(this));
    { titulo = new Fl_Input(80, 10, 360, 24, "T\303\255tulo:");
    } // Fl_Input* titulo
    { id = new Fl_Input(80, 38, 360, 24, "ID:");
    } // Fl_Input* id
    { btnClear = new Fl_Button(24, 100, 100, 24, "Limpar");
    } // Fl_Button* btnClear
    { btnUpdate = new Fl_Button(147, 100, 100, 24, "Atualizar");
    } // Fl_Button* btnUpdate
    { btnDelete = new Fl_Button(270, 100, 100, 24, "Deletar");
    } // Fl_Button* btnDelete
    { btnInsert = new Fl_Button(394, 100, 100, 24, "Inserir");
    } // Fl_Button* btnInsert
    { titulo_aux = new Fl_Box(132, 133, 255, 30);
      titulo_aux->labelfont(1);
      titulo_aux->labelsize(22);
    } // Fl_Box* titulo_aux
    { browser = new Fl_Browser(24, 169, 470, 277);
      browser->type(2);
    } // Fl_Browser* browser
    { label = new Fl_Input(80, 66, 360, 24, "Label:");
    } // Fl_Input* label
    { arquivo = new Fl_Input(163, 450, 100, 24, "Nome do arquivo:");
    } // Fl_Input* arquivo
    { importar = new Fl_Button(270, 450, 70, 24, "Importar");
    } // Fl_Button* importar
    { exportar = new Fl_Button(346, 450, 70, 24, "Exportar");
    } // Fl_Button* exportar
    { gerador = new Fl_Button(420, 450, 70, 24, "HTML");
    } // Fl_Button* gerador
    { reset = new Fl_Button(468, 3, 50, 24, "Reset");
    } // Fl_Button* reset
    w->end();
  } // Fl_Double_Window* w
}
