// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Browser.H>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_Double_Window *w;
  Fl_Input *titulo;
  Fl_Input *id;
  Fl_Button *btnClear;
  Fl_Button *btnUpdate;
  Fl_Button *btnDelete;
  Fl_Button *btnInsert;
public:
  Fl_Box *titulo_aux;
protected:
  Fl_Browser *browser;
public:
  Fl_Input *label;
  Fl_Input *arquivo;
  Fl_Button *importar;
  Fl_Button *exportar;
  Fl_Button *gerador;
  Fl_Button *reset;
};
#endif
