// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_Window *tela;
public:
  Fl_Button *reset;
  Fl_Box *imagem;
  Fl_Input *participantes;
  Fl_Button *sortear;
  Fl_Box *sorteio;
  Fl_Box *homenagem;
  Fl_Box *xganhador;
  Fl_Box *saidasorteio;
};
#endif
